/* -------------------------------------------- */
/*  IRQ handler enable sw macro                 */
/* -------------------------------------------- */

/* 0=disable(dummy handler), 1=enable */

#define IRQ_WWDG_ENABLE 0
#define IRQ_PVD_ENABLE 0
#define IRQ_TAMPER_ENABLE 0
#define IRQ_RTC_ENABLE 1
#define IRQ_FLASH_ENABLE 0
#define IRQ_RCC_ENABLE 0
#define IRQ_EXTI0_ENABLE 0
#define IRQ_EXTI1_ENABLE 0
#define IRQ_EXTI2_ENABLE 0
#define IRQ_EXTI3_ENABLE 0
#define IRQ_EXTI4_ENABLE 0
#define IRQ_DMA1_Channel1_ENABLE 0
#define IRQ_DMA1_Channel2_ENABLE 0
#define IRQ_DMA1_Channel3_ENABLE 0
#define IRQ_DMA1_Channel4_ENABLE 0
#define IRQ_DMA1_Channel5_ENABLE 0
#define IRQ_DMA1_Channel6_ENABLE 0
#define IRQ_DMA1_Channel7_ENABLE 0
#define IRQ_ADC1_2_ENABLE 0
#define IRQ_USB_HP_CAN_TX_ENABLE 0
#define IRQ_USB_LP_CAN_RX0_ENABLE 0
#define IRQ_CAN_RX1_ENABLE 0
#define IRQ_CAN_SCE_ENABLE 0
#define IRQ_EXTI9_5_ENABLE 0
#define IRQ_TIM1_BRK_ENABLE 0
#define IRQ_TIM1_UP_ENABLE 0
#define IRQ_TIM1_TRG_COM_ENABLE 0
#define IRQ_TIM1_CC_ENABLE 0
#define IRQ_TIM2_ENABLE 0
#define IRQ_TIM3_ENABLE 0
#define IRQ_TIM4_ENABLE 0
#define IRQ_I2C1_EV_ENABLE 0
#define IRQ_I2C1_ER_ENABLE 0
#define IRQ_I2C2_EV_ENABLE 0
#define IRQ_I2C2_ER_ENABLE 0
#define IRQ_SPI1_ENABLE 0
#define IRQ_SPI2_ENABLE 0
#define IRQ_USART1_ENABLE 1
#define IRQ_USART2_ENABLE 1
#define IRQ_USART3_ENABLE 1
#define IRQ_EXTI15_10_ENABLE 0
#define IRQ_RTCAlarm_ENABLE 0
#define IRQ_USBWakeUp_ENABLE 0
#define IRQ_TIM8_BRK_ENABLE 0
#define IRQ_TIM8_UP_ENABLE 0
#define IRQ_TIM8_TRG_COM_ENABLE 0
#define IRQ_TIM8_CC_ENABLE 0
#define IRQ_ADC3_ENABLE 0
#define IRQ_FSMC_ENABLE 0
#define IRQ_SDIO_ENABLE 0
#define IRQ_TIM5_ENABLE 0
#define IRQ_SPI3_ENABLE 0
#define IRQ_UART4_ENABLE 1
#define IRQ_UART5_ENABLE 0
#define IRQ_TIM6_ENABLE 0
#define IRQ_TIM7_ENABLE 0
#define IRQ_DMA2_Channel1_ENABLE 0
#define IRQ_DMA2_Channel2_ENABLE 0
#define IRQ_DMA2_Channel3_ENABLE 0
#define IRQ_DMA2_Channel4_5_ENABLE 0

